container:
  image: smartrent/terraform-ci:0.14.4
  cpu: 0.5

base: &base
  timeout_in: 30m

format_task:
  <<: *base
  format_script:
    - terraform fmt -check -recursive

tflint_task:
  <<: *base
  tflint_script:
    - tflint