container:
  image: smartrent/terraform-ci:1.5.7-1a
  cpu: 1

base: &base
  timeout_in: 30m

format_task:
  <<: *base
  format_script:
    - terraform fmt -check -recursive

tflint_task:
  <<: *base
  tflint_script:
    - tflint --init
    - tflint
