version: 2.1

setup: << pipeline.parameters.run_setup >>


orbs:
  smartrent: smartrent/smartrent@1.1.0
  path-filtering: circleci/path-filtering@1.0.0
  shellcheck: circleci/shellcheck@3.2.0

default:
  terraform_docker_version: &terraform_docker_version
    docker_version: 1.5.7-1
  validate_lint_sec_paths: &validate_lint_sec_paths

parameters:
  run_setup:
    type: boolean
    default: true
  run_shellcheck:
    type: boolean
    default: false
  run_terraform:
    type: boolean
    default: false

workflows:
  wf-setup:
    when: << pipeline.parameters.run_setup >>
    jobs:
      - path-filtering/filter:
          name: Workflow Setup
          base-revision: main
          config-path: .circleci/config.yml
          mapping: |
            .* run_setup false
            .*\.sh run_shellcheck true
            .* run_terraform true

  wf-terraform:
    when:
      not: << pipeline.parameters.run_setup >>
    jobs:
      - smartrent/terraform_format:
          name: Terraform Format
          <<: *terraform_docker_version
      - smartrent/terraform_validate:
          name: Terraform Validate 
          <<: *terraform_docker_version
          matrix:
            parameters:
              validate_path: *validate_lint_sec_paths


  wf-shellcheck:
    when: << pipeline.parameters.run_shellcheck >>
    jobs:
      - shellcheck/check

  wf-tflint:
    when: << pipeline.parameters.run_terraform >>
    jobs:
      - smartrent/tflint:
          name: TFLint 
          <<: *terraform_docker_version
          matrix:
            parameters:
              tflint_path: *validate_lint_sec_paths

  wf-tfsec:
    when: << pipeline.parameters.run_terraform >>
    jobs:
      - smartrent/tfsec:
          name: TFSec 
          <<: *terraform_docker_version
          tfsec_force_pass: "|| true"
          matrix:
            parameters:
              tflint_path: *validate_lint_sec_paths